USE [Payroll]
GO

/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 08/13/2013 12:18:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPLOYEE](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[EMPCODE] [varchar](50) NULL,
	[PASSWORD] [varchar](50) NULL,
	[ROLEID] [int] NULL,
	[PERSON_ID] [int] NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


